import os
import re
import git
from agent.state import AgentState
from agent.tools.github import parse_repo_url, create_pull_request
from agent.tools.crypto import decrypt_token


async def run(state: AgentState) -> AgentState:
    run_id = state["run_id"]
    repo_url = state["repo_url"]
    spec = state["spec"]
    plan = state.get("plan", {})
    test_output = state.get("test_output", "")
    log_events = []

    def emit(msg: str):
        log_events.append(msg)

    emit("Pushing branch and opening pull request...")

    repo_path = f"/tmp/{run_id}"
    branch_name = state.get("branch_name", f"yantra/{run_id[:8]}")

    # Get encrypted token from DB (injected into state by worker)
    encrypted_token = state.get("github_token_enc", "")
    if not encrypted_token:
        emit("No GitHub token available — cannot push.")
        return {**state, "error": "No GitHub token", "log_events": log_events}

    raw_token = decrypt_token(encrypted_token)

    try:
        repo = git.Repo(repo_path)

        # Ensure we're on the right branch
        try:
            repo.git.checkout("-b", branch_name)
        except git.GitCommandError:
            repo.git.checkout(branch_name)

        # Set up remote with token
        owner, repo_name = parse_repo_url(repo_url)
        remote_url = f"https://x-access-token:{raw_token}@github.com/{owner}/{repo_name}.git"

        if "origin" in [r.name for r in repo.remotes]:
            repo.remote("origin").set_url(remote_url)
        else:
            repo.create_remote("origin", remote_url)

        repo.git.push("origin", branch_name)
        emit(f"Branch {branch_name} pushed.")

    except git.GitCommandError as e:
        err = str(e)
        if "already exists" in err:
            # Append suffix and retry
            branch_name = f"{branch_name}-{run_id[:4]}"
            emit(f"Branch existed, retrying as {branch_name}...")
            try:
                repo.git.checkout("-b", branch_name)
                repo.git.push("origin", branch_name)
            except Exception as e2:
                emit(f"Push failed: {e2}")
                return {**state, "error": str(e2), "log_events": log_events}
        else:
            emit(f"Push failed: {e}")
            return {**state, "error": str(e), "log_events": log_events}

    # Build PR body
    files_modified = plan.get("files_to_modify", [])
    files_created = plan.get("files_to_create", [])
    files_list = "\n".join(
        f"- `{f['path']}` — {f.get('reason', f.get('purpose', ''))}"
        for f in (files_modified + files_created)
    )
    pr_title = spec.split("\n")[0][:72] if spec else "feat: YANTRA implementation"

    # Use Claude to generate a clean PR title
    from agent.tools import llm
    title_resp = await llm.complete(
        f"Generate a concise PR title (under 72 chars, starts with 'feat:') for this spec: {spec[:500]}",
        model="claude-haiku-4-5-20251001",
        max_tokens=64,
    )
    pr_title = title_resp.strip().strip('"').strip("'")[:72]

    test_section = "Tests passed." if state.get("test_passed") else f"```\n{test_output[-1000:]}\n```"

    pr_body = f"""## What this does
{plan.get('approach', 'See changed files below.')}

## Files changed
{files_list or '_No files listed in plan._'}

## Test results
{test_section}

## Risks
{chr(10).join(f"- {r}" for r in plan.get("risks", [])) or '_None identified._'}

---
> Generated by [YANTRA](https://yantra.dev) · Run ID: `{run_id}`
"""

    try:
        owner, repo_name = parse_repo_url(repo_url)
        pr_url, pr_number = create_pull_request(
            repo_full_name=f"{owner}/{repo_name}",
            token=raw_token,
            branch_name=branch_name,
            title=pr_title,
            body=pr_body,
        )
        emit(f"PR opened: {pr_url}")
    except Exception as e:
        emit(f"Failed to create PR: {e}")
        return {**state, "error": str(e), "log_events": log_events}

    return {
        **state,
        "pr_url": pr_url,
        "log_events": log_events,
    }
